### ISSUE TITLE
Dashboard widget display issue on MODX 2.8

### ISSUE THREAD

**Issue by Mark-H** [modmore/Akismet#14]
![Scherm­afbeelding 2023-11-13 om 20 18 13](https://github.com/modmore/Akismet/assets/312944/cc35ebc3-815d-4c47-89d2-7a657b4500c1)

**Comment by muzzwood** [comment]
Fixed for new installs in https://github.com/modmore/Akismet/commit/45dbaec043c1d085ebc69d5fad32c8f9f22f92a2
and fixed via resolver for previous installs in: https://github.com/modmore/Akismet/commit/0a042818b96742f5f3e126e89d1baf3a553b4a9a
