### ISSUE TITLE
Automatically remove forms after a certain period

### ISSUE THREAD

**Issue by Mark-H** [modmore/Akismet#5]
Similar to Scheduler/FormIt, have a way to automatically remove submissions older than a certain amount of time. 

Perhaps a cron-less solution could be to have the Akismet::checkSpam() method run the cleanup once a day based on a timestamp in a dot-file.

**Comment by muzzwood** [comment]
Enabled in https://github.com/modmore/Akismet/commit/b51ee59bb67bbfd91dde9f2dd6eddffa5c265cc1
