### ISSUE TITLE
Refactor Akismet class to allow easier standalone use

### ISSUE THREAD

**Issue by Mark-H** [modmore/Akismet#7]
https://modmore.com/blog/2021/new-akismet-for-modx/#comment-5526800126

Perhaps changing [the Akismet class](https://github.com/modmore/Akismet/blob/master/core/components/akismet/src/Akismet.php) from:

        public function checkSpam($hook): bool

to

        public function checkSpam(array $values, array $config): bool

so that the snippet is responsible for getting the values and setting the error would be easiest to adapt?

Alternatively, pass those values into the constructor.

**Comment by muzzwood** [comment]
Resolved in https://github.com/modmore/Akismet/commit/a0ac414a26feac6c4b562395cec0403e755f3251
